export const APIENDPOINT = {
    getClientesByID: 'api/Clientes/GetAsync',
    Insert: 'api/Clientes/InsertAsync',
    getLogin: 'api/Clientes/GetLoginAsync',
    fileUpload: 'api/Clientes/FileUpload',
    InsertMicroEmpresa: 'api/MicroEmpresas/InsertAsync',
    UpdateMicroEmpresa: 'api/MicroEmpresas/UpdateAsync',
    DeleteMicroEmpresa: 'api/MicroEmpresas/DeleteAsync',
    getMicroEmpresa: 'api/MicroEmpresas/GetAsync',
    getInfoMicroEmpresa: 'api/MicroEmpresas/GetAllAsync',
    Insertpqrs: 'api/PQRS/InsertAsync',
    Updatepqrs: 'api/PQRS/UpdateAsync',
    Deletepqrs: 'api/PQRS/DeleteAsync',
    GetallpqrsByID: 'api/PQRS/GetAllAsync',
    GetpqrsByID: 'api/PQRS/GetAsync',
    InsertParametros: 'api/Parametros/InsertAsync',
    UpdateParametros: 'api/Parametros/UpdateAsync',
    DeleteParametros: 'api/Parametros/DeleteAsync',
    GetallParametrosByID: 'api/Parametros/GetAllAsync',
    GetParametrosByID: 'api/Parametros/GetAsync',
    getDescription: 'api/DescriptionDynamic/GetDescription',
    getFacturaByID: 'api/Facturas/GetAllAsync',
    UpdateFactura: 'api/Facturas/UpdateAsync',
    getPlanes: 'api/Planes/GetAllAsync',
    getPlan: 'api/Planes/GetAsync'
}